#ifndef EMBER_KeyInput_HPP_
#define EMBER_KeyInput_HPP_

namespace Ember
{
    class KeyInput
    {
        public:
            static unsigned int KEY_SPACE;
            static unsigned int KEY_APOSTROPHE;
            static unsigned int KEY_COMMA;
            static unsigned int KEY_MINUS;
            static unsigned int KEY_PERIOD;
            static unsigned int KEY_SLASH;
            static unsigned int KEY_0;
            static unsigned int KEY_1;
            static unsigned int KEY_2;
            static unsigned int KEY_3;
            static unsigned int KEY_4;
            static unsigned int KEY_5;
            static unsigned int KEY_6;
            static unsigned int KEY_7;
            static unsigned int KEY_8;
            static unsigned int KEY_9;
            static unsigned int KEY_SEMICOLON;
            static unsigned int KEY_EQUAL;
            static unsigned int KEY_A;
            static unsigned int KEY_B;
            static unsigned int KEY_C;
            static unsigned int KEY_D;
            static unsigned int KEY_E;
            static unsigned int KEY_F;
            static unsigned int KEY_G;
            static unsigned int KEY_H;
            static unsigned int KEY_I;
            static unsigned int KEY_J;
            static unsigned int KEY_K;
            static unsigned int KEY_L;
            static unsigned int KEY_M;
            static unsigned int KEY_N;
            static unsigned int KEY_O;
            static unsigned int KEY_P;
            static unsigned int KEY_Q;
            static unsigned int KEY_R;
            static unsigned int KEY_S;
            static unsigned int KEY_T;
            static unsigned int KEY_U;
            static unsigned int KEY_V;
            static unsigned int KEY_W;
            static unsigned int KEY_X;
            static unsigned int KEY_Y;
            static unsigned int KEY_Z;
            static unsigned int KEY_LEFT_BRACKET;
            static unsigned int KEY_BACKSLASH;
            static unsigned int KEY_RIGHT_BRACKET;
            static unsigned int KEY_GRAVE_ACCENT;
            static unsigned int KEY_WORLD_1;
            static unsigned int KEY_WORLD_2;
            static unsigned int KEY_ESCAPE;
            static unsigned int KEY_ENTER;
            static unsigned int KEY_TAB;
            static unsigned int KEY_BACKSPACE;
            static unsigned int KEY_INSERT;
            static unsigned int KEY_DELETE;
            static unsigned int KEY_RIGHT;
            static unsigned int KEY_LEFT;
            static unsigned int KEY_DOWN;
            static unsigned int KEY_UP;
            static unsigned int KEY_PAGE_UP;
            static unsigned int KEY_PAGE_DOWN;
            static unsigned int KEY_HOME;
            static unsigned int KEY_END;
            static unsigned int KEY_CAPS_LOCK;
            static unsigned int KEY_SCROLL_LOCK;
            static unsigned int KEY_NUM_LOCK;
            static unsigned int KEY_PRINT_SCREEN;
            static unsigned int KEY_PAUSE;
            static unsigned int KEY_F1;
            static unsigned int KEY_F2;
            static unsigned int KEY_F3;
            static unsigned int KEY_F4;
            static unsigned int KEY_F5;
            static unsigned int KEY_F6;
            static unsigned int KEY_F7;
            static unsigned int KEY_F8;
            static unsigned int KEY_F9;
            static unsigned int KEY_F10;
            static unsigned int KEY_F11;
            static unsigned int KEY_F12;
            static unsigned int KEY_F13;
            static unsigned int KEY_F14;
            static unsigned int KEY_F15;
            static unsigned int KEY_F16;
            static unsigned int KEY_F17;
            static unsigned int KEY_F18;
            static unsigned int KEY_F19;
            static unsigned int KEY_F20;
            static unsigned int KEY_F21;
            static unsigned int KEY_F22;
            static unsigned int KEY_F23;
            static unsigned int KEY_F24;
            static unsigned int KEY_F25;
            static unsigned int KEY_KP_0;
            static unsigned int KEY_KP_1;
            static unsigned int KEY_KP_2;
            static unsigned int KEY_KP_3;
            static unsigned int KEY_KP_4;
            static unsigned int KEY_KP_5;
            static unsigned int KEY_KP_6;
            static unsigned int KEY_KP_7;
            static unsigned int KEY_KP_8;
            static unsigned int KEY_KP_9;
            static unsigned int KEY_KP_DECIMAL;
            static unsigned int KEY_KP_DIVIDE;
            static unsigned int KEY_KP_MULTIPLY;
            static unsigned int KEY_KP_SUBTRACT;
            static unsigned int KEY_KP_ADD;
            static unsigned int KEY_KP_ENTER;
            static unsigned int KEY_KP_EQUAL;
            static unsigned int KEY_LEFT_SHIFT;
            static unsigned int KEY_LEFT_CONTROL;
            static unsigned int KEY_LEFT_ALT;
            static unsigned int KEY_LEFT_SUPER;
            static unsigned int KEY_RIGHT_SHIFT;
            static unsigned int KEY_RIGHT_CONTROL;
            static unsigned int KEY_RIGHT_ALT;
            static unsigned int KEY_RIGHT_SUPER;
            static unsigned int KEY_MENU;
        public: // Methods
            static bool isKeyPressed(int key);
            static bool isKeyJustPressed(int key);
    };
};

#endif