name: 📊 Static Checks
on:
    workflow_call:

jobs:
    static-checks:
        runs-on: ubuntu-latest
        steps:
            - name: 📦 Checkout
              uses: actions/checkout@v2

            - name: 🚀 Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x'

            - name: 🚚 Install cpplint
              run: |
                pip install cpplint

            - name: 🧪 Run cpplint
              run: |
                cpplint framework/src/**/*.cpp sandbox/src/**/*.cpp include/**/*.hpp
